### ISSUE TITLE
In the NE low code prototype spreadsheet, add a dashboard column to track hours remaining this week 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1032]
## ✨ What new feature do you want to see?
Approval letters state the max hours per week that a child can attend. We should track this on their dashboard based on attendance data from WS. 

## 🧶 Acceptance Criteria
- [x] The NE spreadsheet correctly calculates hours used so far and total approved hours this week in the format X of XX ("e.g. 10 of 45"). 
- [x] This field is included on the "Dashboard to S3" tab - @katelovescode can you please provide any formatting needs and tell us which column you'd like this new field to be in
- [x] I have updated these formulas in the documentation for Kate 

## 🖍️ Implementation Details
We should first implement this in the testing spreadsheet and QA it. Only deploy to the production spreadsheet in coordination with issue #1033 

New column is reflected in the Nebraska V2 mockup here: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=4538%3A16605

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by katelovescode** [comment]
The API is expecting this field to be titled `Hours Attended` (note capitalization). The field mockups and tests show the value written as `1 of 2`, but it can be any string when parsed in via rake task.  Column position doesn't really matter but in my tests it's between `Attendances` and `Status`.

**Comment by JonErvin** [comment]
Hey team (@csprayregen @joseluisrangel-dataheim @JTBassett ) I think this one is ready to QA.  Note that the week begins on Sunday (per guidance from NECC on 3/22)

### Summary of updates:
**Child-level Data**
- NEW Authorized Weekly Hours field

**Created Daily Schedule**
- NEW Scheduled Hours (for Approval) field

**Daily Calculation**
- NEW Scheduled Hours field
- Adjusted 5 fields to better handle missing checkout data.  Previously, the model assumed one full day and allowed the hours field to error out.  As of this edit, the model assumes the child attended (1) the scheduled hours if applicable OR (2) 8 hours, if no valid schedule.  The 5 adjusted fields are: CalculatedMinutes, CalculatedHours, DailyUnits, HourlyUnits, and MissingCheckout.

**Summary By Child**
- 2 NEW date variables: CurrentWeekStart, CurrentWeekEnd
- 2 NEW Hourly Units fields: CalculatedHoursThisWeek, ApprovedHoursThisWeek

**Dashboard**
- NEW column for Hours Attended
- Dynamic header to show CurrentWeekStart (Sunday of current week) and CurrentWeekEnd (Saturday of current week)

**Dashboard to S3**
- Hours Attended field in format `1 of 2` (thanks Kate for the clear guidance here)

**Comment by JonErvin** [comment]
Also team, beyond those changes above, there's a few other new fields that don't directly impact the new dashboard field but may be useful in order to flag any weeks where attendance exceeds weekly limits in a given month.  Would be great to get eyes on this too so we can use if needed down the road.  Specifically, this is:

**Daily Calculation**
_Six columns at the far right of the table in orange_
- Year
- Week Number
- Total Hours this week
- Weekly Limit
- Status ("OK" or "Exceeded Weekly Limit")
- Unique Status (to summarize in SummaryByChild)

**Summary By Child**
- Number of weeks over approval limit this month

**Comment by JTBassett** [comment]
Hey Jon, I just reviewed it and the changes look great! I just had a couple questions / points to follow up on.

1) Daily Calculation Tab: With the Calculated Minutes field there is a case where you have "no end time" when there is no check out. Should this also show that same result in the Calculated Hours field?
2) Summary By Child Tab: 
- I can't seem to find the CalculatedHoursThisWeek and ApprovedHoursThisWeek fields
- I could use a quick walkthrough for the "Number of weeks over approval limit this month" calculation as it is a pretty hefty formula

Once we're on the same page with those points, we should be good to go for this since Jose already reviewed it as well

**Comment by JonErvin** [comment]
Hey thanks @JTBassett!  Appreciate the questions.

To the first one - good spot, this is intentional.  With this update, the `Calculated Hours` field becomes important to track the number of hours a child attends in a given week.  This feeds `Calculated Hours This Week` (which is in column T at the moment to your second question) and ultimately the `Hours Attended` output on the dashboard.  Therefore, calculated hours needs to be a number and, in the event of no check-out recorded, needs an estimated value.  However, I could imagine situations where a provider wants to understand where the hours came from (say the child doesn't check out and we assume 8 hours, but in reality the child attended for 6) - to help us troubleshoot down the road, I used the "no end time" string in calculated minutes as a reminder the hours are estimated rather than actual.  There's probably a more robust way to do this, and there are already error flag on the dashboard, but I figured this would be helpful enough for now.

And then, yeah I agree that Number of Weeks formula is really hefty.  I'll need to write up some documentation for it but what its essentially doing is filtering the final column of Daily Calculation to return an array of values that meet a set of criteria (date range, child ID, and overage flag).  Then it removes duplicate values to return only one value for each week the child exceeded the limits and finally counts the length of the array.  Happy to talk through with you as well!
