### ISSUE TITLE
In the NE low code prototype spreadsheet, replace the Transportation column in the dashboard table with Family Fee

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1037]
## ✨ What new feature do you want to see?
The transportation column will be deleted from the table on the dashboard. This should be replaced with a column that says the family fee for the child for the month. This should be a static number pulled from the approval letter that does not change over the course of the month. 

## 🧶 Acceptance Criteria
- [x] Transportation revenue is removed from the dashboard table and S3 upload tab
- [x] Family fee is added to the dashboard table and S3 upload tab - this should be a decimal and should use the column that Transportation Revenue currently uses.  The header name should be `Family Fee` <-- the api is expecting this capitalization format
- [x] The family fee will be added specifically for the child who has the most hours scheduled in their Wonderschool schedule. This is based on DHS clarification that the family fee comes from the child with the most hours of care. --> update: this will be based on the DHS approval letter, not the WS schedule
- [x] This change is documented in the NE formulas doc for Kate 

## 🖍️ Implementation Details
Still an open policy question: how best to allocate family fee across children. Be clear in documentation for now on what assumptions we're making until we can get an answer from DHS. 

We should first implement this in the testing spreadsheet and QA it. Only deploy to the production spreadsheet in coordination with issue #1036 

New column is reflected in the Nebraska V2 mockup here: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=4538%3A16605

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by csprayregen** [comment]
Updated mockup to match: 
![image](https://user-images.githubusercontent.com/26717304/112398058-4c3c3600-8cd1-11eb-8ab7-c8f291fb69eb.png)

**Comment by JTBassett** [comment]
@joseluisrangel-dataheim This looks good to me after you delete the old transportation column!

**Comment by JonErvin** [comment]
Hey @joseluisrangel-dataheim, I had a chance to go through this update.  Thanks for pulling this together.  I have a few thoughts and questions:
- I think the biggest change here is actually changing the way that the family fee is allocated.  Instead of splitting the fee across all children in the case, we're applying to just one child.  I like how you set this up in the Child-Level Data tab, and it looks like it calculates correctly for the new column.  However, we'll need this to flow through to the Earned Revenue, Estimated Revenue, Scheduled Revenue columns as well.  Each of these values subtracts the family fee (this happens in the (2d) section of Summary By Child).  I think the simplest solution would be to change the formula in the `Family Fees` field (column BA in Summary By Child) to lookup the value from the new Family Fee column you created in Child-Level Data
- Right now, I think your formula determines the child with the majority of hours using the Authorization data (in Child-Level Data) rather than the Wonderschool schedule.  I think the card suggests using Wonderschool schedule instead.  However, I actually think your approach works best here - this data will be more static than Wonderschool schedules I imagine and therefore might be more predictable / easy to use (for example, I imagine its easy for a provider for the family fee to be taken from the same child each month).  The math for using Wonderschool schedules would likely also be a little more complex and the data is a little less robust (e.g., we don't have end dates for any of the WS schedules) @csprayregen thoughts here?  Think authorizations works fine?
- I really like how you've been creating these boolean `Active` columns.  In your `Holds Majority` formula, I think you'll want to incorporate the `Active` boolean to account for inactive approvals.  For example, if a child gets a new approval letter, we would not the old inactive approval to be considered the majority.  I think you can accomplish this with one more condition in the MAXIFS()
- Finally, we might also want to remove the `Allocated family fee` from Family-Level Data and from Inputs to S3.  Its not necessary for the model to function, but I think it would help prevent us from getting confused down the road

Let me know if you have any questions here - happy to jump on the phone today or tomorrow to talk through!
