### ISSUE TITLE
I can mark a child as inactive 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1124]
## 💻 Implementation Details

- [x] I can see the "actions" column to the far right of my table
- [x] For every child, I can click "Mark Inactive"
- [x] When I click Mark Inactive, a dialogue box appears for that child with copy that matches the mockup
- [x] Within the dialogue box, I can select the reason for marking inactive from the three offered in the mockups
- [x] Within the dialogue box, I can select the date the child will become or has become inactive (using the calendar ant component from the mockup) --> @cjhaddad I'm getting a bug here. When I click a date the first time, it doesn't seem to register in the field. I have to open the calendar a second time and select a date, and then I'm able to continue selecting different dates after that. This repeats for multiple kids for Nebraska in English and Spanish, and for Illinois in English only (but not in Spanish - weird!). 

- [x] I must select a reason and a date to click "Mark Inactive" 
@cjhaddad I'm getting a related bug here too (see screenshot below). I seem to be able to proceed without the date I've selected actually showing up in the field. 

<img width="518" alt="Screen Shot 2021-06-04 at 3 43 08 PM" src="https://user-images.githubusercontent.com/26717304/120860612-92bcd500-c54b-11eb-98a6-ab8b81c7a810.png">

- [x] I can click "Mark Inactive" to mark that child inactive
- [x] The above AC work in all state (NE and IL)
- [x] The above AC work in English and Spanish
- [x] I have checked for accessibility (see below)

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Figma link** https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=4979%3A23572
Spanish translation: https://docs.google.com/spreadsheets/d/1d0RPc9PXvTCFpq8bfkZxgNL35MEpX5s8EvBwqex8564/edit#gid=608766852

**Comment by csprayregen** [comment]
@rebeccakarasiktw please add a link to the Figma when final

**Comment by nneka-nu** [comment]
@katelovescode I'd like to work on this issue.

**Comment by csprayregen** [comment]
Hi @nneka-nu jumping in as Kate is on vacation this week. Candice is going to take this one, but please do jump in on the other one you said you'd like to take today - I already moved it to the In Progress column. Thanks so much for your work here!

**Comment by nneka-nu** [comment]
Hi @csprayregen, no problem. I've actually finished that other task (cause it was so simple) and made a pull request.
I'll choose another.
Can I work on a task that's labeled `Needs Spanish`, or should I wait till it says `Has Spanish`?

**Comment by csprayregen** [comment]
Great @nneka-nu here are a couple that might be good to start on. If you tag me and let me know you're picking something up with that tag, I can prioritize getting the Spanish translated. 

https://github.com/pieforproviders/pieforproviders/issues/1150

https://github.com/pieforproviders/pieforproviders/issues/985

**Comment by nneka-nu** [comment]
Thanks, @csprayregen.

**Comment by cjhaddad** [comment]
@katelovescode I assume an API call needs to be made when the row/ child is marked as 'inactive' -- what endpoint? and I also assume a new field will be added to the cases object showing the child as either active or inactive

**Comment by rebeccakarasiktw** [comment]
Hey @cjhaddad I have a couple of things I noticed, not sure if they are reliant on the back-end work being done or not so I'll put them all here for now:

1. In IL dashboard, the child's name should appear in the title of the modal
<img width="949" alt="1" src="https://user-images.githubusercontent.com/26929739/118501072-5d645a80-b6f6-11eb-8268-92c7ead3f90c.png">

2. In Spanish the "mark inactive" link in the table, title in modal, and CTA in modal, should be "Desactivar" (unless @csprayregen has Spanish text somewhere else). 
<img width="686" alt="2a" src="https://user-images.githubusercontent.com/26929739/118502288-918c4b00-b6f7-11eb-99a1-79408e95bccc.png">

3. In the modal pop-up change "Reason for making inactive" to "Reason for marking inactive" (see 1st screenshot)

4. If I open the modal, select a reason, close without saving, then open the modal again, the original reason that I chose still stays there. The expected behavior should be that I go back seeing the "Reason for marking inactive" text.
<img width="1792" alt="4" src="https://user-images.githubusercontent.com/26929739/118502406-ac5ebf80-b6f7-11eb-9d64-2cdba477bacd.png">

5. Once I have chosen a reason, the selected reason is in black text but it should be blue. (see screenshot for #4)

**Comment by csprayregen** [comment]
Hey @cjhaddad adding on here:

- [ ] The Mark Inactive text in each child's row does not translate to Spanish (Marca Inactivo)

**Comment by cjhaddad** [comment]
@rebeccakarasiktw and @csprayregen cool! will get on these!
