### ISSUE TITLE
Bug on updated provider payment rate

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1155]
## 🤬 What's wrong?
We recently updated a provider's approval rate, because she got an increased QRIS rating. Two issues have come up:

1. Our documented payment rates are slightly lower than those that appear on her approval letter. 
2. This changes her estimates for previous months, which seems fine for the spreadsheet, but we want to make sure this doesn't work that way in the app, and that documentation for engineering makes that clear. 

UPDATE: Given the finding in the comment below, please make sure to meet these AC:
- [x] Update QRIS formula in the test spreadsheet
- [x] Update QRIS formula in the production spreadsheet
- [x] Update documentation on QRIS formula for engineering
- [x] Add date ranges for providers' QRIS ratings to have accurate point in time estimates - in the testing spreadsheet
- [ ] Add date ranges for providers' QRIS ratings to have accurate point in time estimates - in the production spreadsheet
- [x] Update documentation for engineering to reflect the addition of date ranges for QRIS ratings

## 💻 Browser Info

Please complete the following information if accessing the app from a computer:

## 🏓 Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by JonErvin** [comment]
Instead of increasing 5% linearly (i.e. 5% step 3, 10% step 4, 15% step 5) the providers actually multiply the old rate by 1.05 - you essentially have slight compounding of the 5% bump.  The net effect is that you have a 5% increase for step 3, 10.25% for step 4 and 15.76% for step 5.  This different interpretation of the [guidance](https://www.education.ne.gov/stepuptoquality/providers-educators/benefits/#:~:text=If%20your%20program%20receives%20child,for%20each%20additional%20step%20achieved) matches up with the authorized rates from providers - will update in the model

**Comment by JonErvin** [comment]
Follow-up on this - missed the acceptance criteria for adding date ranges.  Working through this edit in testing now, will update once complete for QA / moving to production

**Comment by JonErvin** [comment]
### Summary of Changes
Overall, updates (1) change rates math, (2) add fields for date range for provider QRIS info, (3) update formulas to check against that date range, and (4) remove dashes in field names to enable those new formulas.  Details below.

### Reference Data
- Updated Table 4: Accreditation and QRIS Ratings to include revised math (per comment above)
- Updated Table 2: Age Groups to remove dashes. "Pre-school" to "PreSchool" and "School-Age" to "SchoolAge" (necessary for updated lookup formulas in Daily Rate and Hourly Rate calculations)
- Updated Table 6 and Table 7: Rates Tables to remove dashes in age group name.

### Inputs
**Provider-level Inputs**
- NEW: `QRIS Begin Date` and `QRIS End Date` fields
- NEW: `Provider Entry ID` field (used in Provider-level Calc as a lookup ID)

**Inputs to S3**
- NEW: `QRIS Begin Date` and `QRIS End Date` fields

### Calculations
**Provider-level Calculations**
- NEW: `Provider Entry ID` field (used as a unique ID for lookup since provider name may now appear twice)
- NEW: `Begin Date` and `End Date` fields
- Changed `Business Name`, `Rates Column`, and `QRIS bump` to lookup based on `Provider Entry ID`
- Changed headers and associated named ranges to remove dashes. "Pre-school" to "PreSchool" and "School-Age" to "SchoolAge" 

**Daily Calculation**
- NEW: `Check - Number of Valid Rates` field (used to ensure only one valid rate for a given attendance day - errors are elevated to Dashboard error checkers)
- Updated `Daily Rate` and `Hourly Rate` to compare attendance to valid date range for rates and select the active rates from Provider-level Calculations
-  Updated `Age bracket` formula to remove dashes. "School-Age" to "SchoolAge" 

**Summary By Child**
_Same three updates as Daily Calculation_
- NEW: `Check - Number of Valid Rates` field (used to ensure only one valid rate for a given attendance day - errors are elevated to Dashboard error checkers)
- Updated `Daily Rate` and `Hourly Rate` to compare attendance to valid date range for rates and select the active rates from Provider-level Calculations
-  Updated `Age bracket` formula to remove dashes. "School-Age" to "SchoolAge" 

_Additional updates_
- Updated `Activity Fee Rate`, `Transportation Rate`, and `Enrollment Fee` to check against valid date range and select the active rates from Provider-level Data

**Dashboard**
- NEW: `Multiple valid provider rates?` in error checker

**Comment by JonErvin** [comment]
Hey all this is nearly ready for production.  Couple quick things.  @joseluisrangel-dataheim or @JTBassett could one of you pick up the QA for this?  Would love a quick flip through to confirm the changes above work as expected.

@katelovescode I added two fields to Inputs to S3, `QRIS Begin Date` and `QRIS End Date` both date values in the format yyyy-mm-dd.  This allows us to update a provider's QRIS rating while keeping the historical info (e.g., in May provider upgraded to QRIS Level 4, but March and April records should still use QRIS Level 3 rates). Is this easy enough to add to the parser?

@csprayregen Just for visibility

**Comment by katelovescode** [comment]
@JonErvin Yeah, this should be easy enough to add to the parser, but we'll also need backend logic to handle it, can you make a backend ticket and drop it into the To Do column for me?

**Comment by JonErvin** [comment]
Awesome thanks!  #1268 is the ticket, let me know if anything else is helpful here

**Comment by JTBassett** [comment]
Hey @JonErvin, I went through it and it looks great, but I just have one question. On the new "Multiple valid provider rates?" counter in the Dashboard tab, why do you count the number of invalid schedules on both the summary page and the daily calculation page. Wouldn't that be mixing different types of counts? Maybe I need to better understand what you are looking to show.

**Comment by JonErvin** [comment]
Also thank you @JTBassett!

**Comment by JTBassett** [comment]
I think what you did makes since - like you mentioned, the important thing is that error(s) occurred and the exact count is less important. Breaking them up might just detract from the idea since there's already a decent number of counters. You've got a 👍 from me!

**Comment by JonErvin** [comment]
@csprayregen I think this one is good to go in the production sheet!  Would love a quick QA to make sure everything looks right.  

You should see that updated QRIS number (~16% vs 15% for Step 5).   Also, the provider that upgraded from step 4 to step 5 in April should be at Step 4 (~10%) through 3/31/2021 and at Step 5 (~16%) beginning on 4/1/2021 - this will allow us to have an accurate historical record.

Let me know if you have any questions or want to talk through anything here!

**Comment by csprayregen** [comment]
@JonErvin sorry for the delay - this looks good! Closing this one out
