### ISSUE TITLE
Optimize daily upload process

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1410]
## 🇺🇸 States this change applies to
- [ ] Nebraska
- [ ] Illinois

## 💻 Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by JonErvin** [comment]
Alright @csprayregen think I have a draft solution here.  Here's what I think the current process looks like and where I think we can cut out steps ([2021 07 - Pie upload process](https://docs.google.com/document/d/1IvMNz6mjZ7K40kuDK-jEgk2DC6ANSGuBfuT-vj3JGfA/edit?usp=sharing)).  The gist is that instead of all the manual sorting, checking IDs, and checking for changes, Sheets can just do it for you - you would just copy/paste the raw data from WS into a new helper tab.  The testing sheet should have this working now: [NE Testing](https://docs.google.com/spreadsheets/d/1FKw4C6Cw0oQT6YJX8GoSZ5p4-7YaOGIxDe20tb-SaSM/edit#gid=139522515)

Can talk more tonight!

**Comment by csprayregen** [comment]
@JonErvin this is amazing!!! Will this pick up changes to records when they've been edited? Additionally, would I be copying and pasting all the records every day, or just new ones?

**Comment by JonErvin** [comment]
Hey team just confirming this is now updated in the [docs](https://docs.google.com/document/d/1IRbjS3mgbzTA8yzR38ewg10sTsfKN-HUxr9WyLpbvAw/edit#).  The one open question was a data discrepancy for 7560 and 7561.  Confirmed that there are two extra attendance for each in Wonderschool, but they're from 2/25/21 and 2/26/21 which was right as they were being onboarded.
