### ISSUE TITLE
Investigate absences - do they count towards your authorization limits?

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#1766]
## 📋 Summary

We need to update the spreadsheet to incorporate absences in the authorization period limits (i.e. full days and part days). 
 We think that 5 regular absences (as opposed to COVID absences) per month should count as "used" time, but *only* when displaying the remaining authorized units per authorization period.  This ticket should cover the research and the implementation in the spreadsheet of these changes.  Backend ticket #1767 should be updated as a result of this research.

Open question: should absences *always* be counted as a full day unit in the case of subtracting from authorized hours?  They are currently being generated as full-day units w/ 8 hours duration.

## 🇺🇸 States this change applies to
- [X] Nebraska
- [ ] Illinois

**Comment by csprayregen** [comment]
Here is the response from the state, also documented in #1767 , where we will implemented needed changes to the rules: "The provider may bill the full authorized amount for times that the child is absent on a scheduled day, up to five times per month. For example, if the child is approved for 40 hours per week and they have already received 40 hours of care for the week, it would not be allowed to bill an absent day for that week since they have already met their approved hours per week. The absent days that are billed do count towards the total units approved."
