### ISSUE TITLE
Change default sort in dashboard, view attendance, & input attendance tables

### ISSUE THREAD

**Issue by rebeccakarasiktw** [pieforproviders/pieforproviders#2018]
## ✨ What new feature do you want to see?
All of my tables default to a sort by child's last name, alphabetically. 

## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

## 🧶 Acceptance Criteria
- [ ] The dashboard table sorts alphabetically, by Child Last Name
- [ ] The View Attendance table sorts alphabetically, by Child Last Name
- [ ] The Add Attendance table sorts alphabetically, by Child Last Name
- [ ] This works in English and Spanish 
- [ ] Check for accessibility 
- [ ] Check for impact on performance

**Comment by twinsfan421** [comment]
@katelovescode After looking at this closer,  there is an issue with children having a  full_name attribute and not saving a first and last name separately.  I could do something like this in the with_dashboard_case scope:
`            .select("children.id, children.active, children.inactive_reason, last_active_date, business_id, wonderschool_id, full_name, date_of_birth, split_part(full_name, ' ', 2) as last_name").order(last_name: :desc)`
            where I use split_part to add a last name for the order query.  Or I could use sort_by method after it has already been queried.   Neither option is great in my opinion.
            
  I noticed on the dashboard table header, if you click on the child header, you can sort by the last name. Another option is you could implement the same style table with sortable headers for the view attendance and edit attendance? Let me know what you think

**Comment by katelovescode** [comment]
Ultimately I was trying to be inclusive as possible because not every culture has a first name and a last name; but I can see how this is challenging right now and has kind of become an obstacle.  @rebeccakarasiktw @csprayregen we could make some assumptions here on where to split names, but the spreadsheet would have to be changed too, I believe?  I'm sure Jon could do that quickly.  @twinsfan421 could then split the names we already have - there are only 183 kids right now so we could manually fix anything that's wonky.  That means the work for this PR will need to:
- split all the names into two fields
- either:
  - remove the full_name field and refactor the front-end to work with both first_name and last_name fields
  - leave the full_name field, return all three fields, and refactor the front end to *sort* on the last_name field

@twinsfan421 thoughts on this?  @csprayregen / @rebeccakarasiktw ?

**Comment by csprayregen** [comment]
I defer to the other tagged folks on this one!

**Comment by twinsfan421** [comment]
The .order(last_name: :desc) would return the children sorted by name but is creating the additional field just to do so and is not as efficient.  If you really want to order by last name,  I would recommend splitting the full_name to separate first and last name.  Or using the sort option on the data table like you do with the dashboard table already and implementing that to the other tables.

**Comment by katelovescode** [comment]
@JonErvin Is it difficult to split the two fields in the onboarding spreadsheet and all the related sheets that rely on Full Name?  I would assume we'd want to do that as well.  Personally I'm in favor of splitting full_name into two fields but @cjhaddad should be aware as well.

Likely Steps to fulfill this issue:
- migration to add first_name and last_name to children
- migration to copy the split existing full_name field data into the first_name and last_name fields for existing records
- change onboarding spreadsheet and script to accept first_name and last_name fields instead of full_name
- change front-end to use first_name and last_name anywhere it's using full_name
- change back-end to use first_name and last_name anywhere it's using full_name
- migration to remove full_name field from table
- change backend to return child records/case records sorted by last name

I would like to split this work into separate tickets for each of these steps, because they're easily isolated.

Feedback I need:
- Am I missing any steps we'll need to get this to work from a technical perspective? (@cjhaddad @twinsfan421 )
- Am I missing any context from the user's perspective (@rebeccakarasiktw @csprayregen )

If we're all 👍🏼  on this (feel free to react to this instead of commenting if you think this is good to go!), then I'll write the new tickets ASAP and get them prioritized in order and marked blocked where they can't be worked on until other work is closed.

**Comment by cjhaddad** [comment]
This works for me. The UI for sign-up should change then, yes? There will be two inputs -- one for first name and one for last name, correct? cc: @rebeccakarasiktw

**Comment by katelovescode** [comment]
@cjhaddad this is only for children, not for users.

**Comment by cjhaddad** [comment]
@katelovescode  boop! sign-up on the brain!

**Comment by twinsfan421** [comment]
> @JonErvin Is it difficult to split the two fields in the onboarding spreadsheet and all the related sheets that rely on Full Name? I would assume we'd want to do that as well. Personally I'm in favor of splitting full_name into two fields but @cjhaddad should be aware as well.
> 
> Likely Steps to fulfill this issue:
> 
> * migration to add first_name and last_name to children
> * migration to copy the split existing full_name field data into the first_name and last_name fields for existing records
> * manually edit any kids names that got split strangely
> * change onboarding spreadsheet and script to accept first_name and last_name fields instead of full_name
> * change front-end to use first_name and last_name anywhere it's using full_name
> * change back-end to use first_name and last_name anywhere it's using full_name
> * migration to remove full_name field from table
> * change backend to return child records/case records sorted by last name
> 
> I would like to split this work into separate tickets for each of these steps, because they're easily isolated.
> 
> Feedback I need:
> 
> * Am I missing any steps we'll need to get this to work from a technical perspective? (@cjhaddad @twinsfan421 )
> * Am I missing any context from the user's perspective (@rebeccakarasiktw @csprayregen )
> 
> If we're all 👍🏼 on this (feel free to react to this instead of commenting if you think this is good to go!), then I'll write the new tickets ASAP and get them prioritized in order and marked blocked where they can't be worked on until other work is closed.

Looks good from a technical perspective.

**Comment by katelovescode** [comment]
@twinsfan421 I'll write new tickets for each of these tomorrow and get them prioritized in todo.  Cheers!

**Comment by katelovescode** [comment]
I can't really "upgrade" this to a milestone so I'm moving the description into the milestone description for the experiment, and closing this as duplicate
