### ISSUE TITLE
I see the correct authorization period for all my children

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#2033]
## ✨ What new feature do you want to see?
To onboard children on the same case with different authorization periods, we had to manually change the authorization periods. This will now be confusing for the user to read different authorization periods that don't match the auth letter. 

## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

## 🥧 Implementation Details

TBD: Do we need to retroactively fix the kids we duct-taped in?

**Comment by katelovescode** [comment]
I think this is going to need a few tickets:
- update spreadsheet to use different dates for kids approval periods if we're not already doing that
- add effective_on and expires_on to child_approval
- update onboarding importer to assign the kids' dates to child_approval instead of approval
- change authorization period calculations to use child_approval effective_on and expires_on instead of approval dates
- verify that if we're still using effective_on and expires_on from the approval anywhere in the code that it makes sense <spike>

**Comment by katelovescode** [comment]
Closing in favor of the [milestone](https://github.com/pieforproviders/pieforproviders/milestone/35)
