### ISSUE TITLE
View Attendance Tags - show billable numbers

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#2431]
## 📋 Summary

Update the tags on the view attendance page to show the correct (rounded) billing number of hours and days so providers can use that page to directly bill.

- Wants to see 2.75 hours, not 2 hours and 45 minutes. If I’m going to manually add it up, might as well stay in the system I have.

## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

## 💻 Implementation Details

The rounding we use is already in place in the dashboard calculations; we just want to display these numbers in the existing "hours" and "full day" tags.  The service days endpoint returns tags "hourly" and "daily" - we want to return (for example) "4.75 hours" and "1 full day".  See `app/services/nebraska/daily/hours_duration_calculator.rb` and `app/services/nebraska/daily/days_duration_calculator.rb`, but the rule in words is:
- up to 6 hours is charged hourly (rounded up to the nearest 15 minutes, display as decimal)
- between 6 and 10 hours is 1 full day
- above 10 hours is 1 full day plus the additional hours above 10 (rounded up to the nearest 15 minutes, display as decimal)
- the max is 18 hours (1 full day + 8 hours) - anything over that should display as if it were 18 hours

**Comment by rebeccakarasiktw** [comment]
Hi @twinsfan421 @katelovescode this looks good but can we make a couple of small tweaks, see comments / screen shot below:

<img width="312" alt="Screen Shot 2022-04-19 at 13 21 57" src="https://user-images.githubusercontent.com/26929739/164070701-dfc40dd1-41b3-4e57-b568-8cb6cc2cc101.png">

- If the hour is a full hour i.e. 2 or 3 hours, can we get rid of the ".0" afterwards?
- If it is just 1 hour, can it say "1 hour" instead of "1.0 hours" ie make the word hours singular?
