### ISSUE TITLE
Update IL algorithms to include special COVID rules

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#412]
## ✨ What new feature do you want to see?
Are the rules in IL different right now for either children's excused absences or provider closure? If so, do we need to update our algorithm to account for these changes?

**Comment by jacqzwy** [comment]
- The 80% threshold has been lowered to 50%. According to 
[ccap-updates - covid19.pdf](https://github.com/pieforproviders/pieforproviders/files/5431811/ccap-updates.-.covid19.pdf)
 it is approved till December 2020. Will update our spreadsheet to reflect that. 

- Rules for remote learning: "providers can change any part-time days on their child care certificates to full days, and write the reason for the change as 'remote learning.'" I'm assuming that this adjustment will be made on the provider's end rather than on our end, but maybe some sort of reminder on the provider data upload spreadsheet to remind providers to make that adjustment would be helpful.

**Comment by csprayregen** [comment]
Thanks @jacqzwy - on point 2, I think that's an interesting idea. I wonder if we can add that somewhere on the dashboard, especially if a provider uploads part day attendance. Let's discuss with @rebeccakarasiktw and @hmarcks in our conversation tomorrow!

**Comment by csprayregen** [comment]
@JonErvin this is one of the issues I just Slacked you about
