### ISSUE TITLE
Update IL algorithms to include school age children

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#414]
## ✨ What new feature do you want to see?
Include this additional age band in our algorithm. Given COVID special situations, this should also account for school age children who attend for a full day.

**Comment by jacqzwy** [comment]
We would need more information from providers on whether a child is enrolled in kindergarten or school to determine if a child is considered a school age child. This is not currently captured in the provider data upload template.

The calculation procedures for days eligible and attended are also a little confusing to me. This is my interpretation of the procedure for school age children ([school_age_children.pdf](https://github.com/pieforproviders/pieforproviders/files/5405605/school_age_children.pdf)), @csprayregen let me know if it matches what you know.

School aged children are usually approved for part time days and 0 full time days:
- If a child attends x full time days, then set eligible full time days = x
- Deduct eligible part time days by x 

If for some reason, child is approved for full time days:
- I'm assuming that the above adjustment only happens when the child attends full time on an eligible part time day? 
- Assuming yes, then we need the schedule for eligible full time and part days to determine when this happens because we can't infer this on the basis of number of days eligible/ attended alone.

**Comment by csprayregen** [comment]
@jacqzwy on the first item, I've created a separate onboarding spreadsheet just for our IL pilot and added a column to it asking if a child is school age: https://docs.google.com/spreadsheets/d/1JPK6r69yEO_U3Eu-nFc_soq9r7MjcsPEZMc_IAMtAwA/edit#gid=246587558

**Comment by csprayregen** [comment]
@jacqzwy I think your interpretation is correct, but I would do the following on our end:

1)Add school age days as a separate rate type in algorithm (unless this is always the same dollar amount as part days - have you figured this out?)
2) Collect # of school days approved in onboarding spreadsheet - added (see link above) but will remove if it's not functionally separate from school age days
3) Track attendance, attendance risk, and predict revenue (Related question: does the 80% threshold work the same for the school age rate type? This isn't referenced in that part of the manual.) 
4) If a provider submits an attendance report that includes full time attendance, assume it was proper (i.e. a covered holiday or school closure day) and reduce part time eligible days as indicated in the link. 
5) In these cases, flag that assumption for providers (e.g. "You reported a full time day on October 12, 2020. If school was not closed, you may not be reimbursed for all of this care." 

This question of school closure is likely the biggest driver of changes in rules for COVID - #412. I don't think we need to have all of these nuances 100% implemented in the no code MVP to start deploying this with providers, but I'd like to understand how COVID factors into it before we make a judgment call on what we implement immediately and what we de-prioritize.

**Comment by jacqzwy** [comment]
1. Current rate chart does not have a separate rate for school-age so this is just the part day rate
2. It seems like the manual is treating part day = school day, so maybe we can just assume that part day for a school age child = school day? Although I'm not sure if a school age child can be approved for both part days and school days? Eg. if a child needs part time care on a day that isn't a school day. I don't think the manual addresses this specifically.
3. It seems like the manual is treating school day rate = part day rate so I think we can assume that school day = part day and the same threshold calculations for part and full days would apply. If however there can be a situation where a child is approved for part days and school days separately, then maybe it's treated as a separate rate type? The manual isn't clear on this. 
4/5: Makes sense in the 'normal' case where a child is approved for 0 full days. However, in an 'exception' case where a child is approved for some full days, we wouldn't know whether a full day attended comes from an approved full day or an approved school day that turned into a full day because of a holiday/ school closure. This in turn means we don't know whether to deduct from approved part days.

**Comment by csprayregen** [comment]
@jacqzwy 

1. I see that there is no separate rate listed. Let's assume they're the same amount for now, but I'd love to verify this. Adding a card to the backlog: #467 
2. Agreed - perhaps revisit after we close #467 
3. Yes, let's assume the same for now.
4/5: Good point. I think for now we can assume that - if the child is approved for full time days - any full time days reported come out of that approval. If the provider reports more full time days of care delivered, then we should flag that this is only valid if it was a holiday.

**Comment by csprayregen** [comment]
@JonErvin this is one of the issues I just Slacked you about
