### ISSUE TITLE
Create a scheduled job to populate staging database with NE attendance data

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#584]
## 📋 Summary
We anticipate that our MVP Release 1 will not include spreadsheet upload. Instead, users will email us spreadsheets, and we will populate the database on their behalf. 

## 💻 Implementation Details
The fields we will get and the sources we will get them from - as currently scoped in our pilot - are laid out in detail here: https://docs.google.com/document/d/15wOle6y3JDdarluwXCv0UrjQoZ-jnDTpBcBCw8fI-GM/edit

I'm open to discussion on the best way to consolidate these in the upload to lighten the engineering load. 

- This should probably be built as a service that gets called by a rake task, and I'd love to make a separate directory called `demo_support` or something similar so this type of functionality is separate from the actual application.

## 🧐 Why tho
So that users can see their data before we finish building spreadsheet upload

**Comment by katelovescode** [comment]
On hold while I wait for AWS account propogation, it's going to take a few days at least.

**Comment by katelovescode** [comment]
@csprayregen Just a heads up - this will be tricky to QA and requires some configuration that won't be ready until Wednesday when we get our real AWS Organization. Even then it'll be pretty much invisible without looking at server logs. If there are bugs with the upload later there's lots of logging in the files that process the attendances and we can write new tickets if something comes up. My preference is to move this to approved rather than QA, thoughts?

**Comment by csprayregen** [comment]
@katelovescode that works for me. I think we should just look carefully at the first few accounts to make sure the information is appearing correctly, since we'll have the original files to compare it to as well.
