### ISSUE TITLE
Update NE formulas to reflect approval letter data fields 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#816]
## ✨ What new feature do you want to see?
Approval letters have different data fields than we had planned for. We need to make sure our formulas match the data inputs we'll get. 

## 🧶 Acceptance Criteria
- [x] Formulas reflect authorized annual hours
- [x] Formulas reflect authorized annual days
- [x] Exceeded Limit status is updated
- [x] Formulas reflect (possible) max hours per week 
- [x] Updates are documented in the formulas doc
- [x] Test cases are updated in the formulas doc 
- [x] Updates are documented in the NE overview doc 
- [x] Open questions are documented in the open questions doc

## 🖍️ Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by JonErvin** [comment]
Going through the [docs](https://docs.google.com/document/d/1IRbjS3mgbzTA8yzR38ewg10sTsfKN-HUxr9WyLpbvAw/edit#), this ticket impacts the following fields:

**(Inputs) Child-Level Data**
-  Authorized Full/Hourly Units: Will need to be adjusted to reflect authorization over varying time periods >1 month.  Related open question (B1 in current doc): Since hours and days do not sum, how do we translate between them?
- Family Fee: Will need adjust to reflect possibility of changing over an authorization period.  Simplest solution is just to break up into two separate authorization periods

**(Calcs) Family-Level Summary**
- Family Fee: Will need to take into account current date given family fee changes over time

**(Calcs) Summary By Child**
PART I: Units
- Authorized Daily Units & Authorized Daily Units: Will be adjusted same as above
- Warning Labels: Will need adjust (e.g., warning when exceeding average units per month)

PART II: Revenue
- Authorized Revenue: Will likely be determined by daily schedule from WS rather than overall totals for period.
- Additional Expected Revenue: Will likely be determined by daily schedule from WS
- Delta, % Delta, and Revenue Indicator: Will likely be calculated as delta from schedule to date (vs current method of comparing forecast to approved).  Pending sample data from WS to confirm this will work

**Dashboard**
- Approved Revenue will change due to change in Authorized Revenue above
- Estimated Revenue will change due to change in Additional Expected Revenue above

**Comment by JonErvin** [comment]
Update 2/7/21: All complete and [documented](https://docs.google.com/document/d/1IRbjS3mgbzTA8yzR38ewg10sTsfKN-HUxr9WyLpbvAw/edit#) EXCEPT for use of authorized units (pending information on how to translate between hourly units and daily units.  Changes include:

**(Inputs) Child-Level Data**
- Family Fee: Removed for Family-Level Data

**(Inputs) Family-Level Data: NEW**
 - Replaces Family-Level Summary.  New place to upload family fee data in onboarding.

**(Inputs) Schedule Data: NEW**
- Wonderschool schedule upload template

**(Calcs) Family-Level Summary: Sheet Removed**
- Family Fee: Will need to take into account current date given family fee changes over time

**(Calcs) Schedule - Units Calculation: NEW**
- Calculated expected units from Schedule Data input sheet

**(Calcs) Created Daily Schedule: NEW**
- Determines an expected number of hourly units and daily units for each combination of child and date.
- This serves as the new baseline for Approved / Expected revenue on the dashboard (replaced Authorized units)

**(Calcs) Summary By Child**
PART I: Units
- Authorized Daily Units & Authorized Daily Units: Currently blank
- Added: Scheduled Daily/Hourly Units in Month
- Added: Remaining Scheduled Daily/Hourly Units in Month 
- Warning Labels: Warning message reflects "scheduled" units instead of authorized

PART II: Revenue
- Authorized Revenue: Currently blank
- Added: Scheduled Revenue, calculated from scheduled daily units and scheduled hourly units
- Additional Expected Revenue: Now determined by daily schedule from WS
- Delta, % Delta, and Revenue Indicator: Now calculated as delta from schedule to date (vs current method of comparing forecast to approved). 

**Dashboard**
- Approved Revenue changed to use scheduled units as baseline
- Estimated Revenue changed to calculate based on remaining scheduled units in month
