### ISSUE TITLE
Final updates to NE spreadsheet template for low code pilot

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#907]
## 📋 Summary
- [x] Create a tab that includes all the dashboard fields for upload to S3. 
- [x] This Dashboard tab should display the numbers cumulatively for the current month. 
- [x] This Dashboard tab should include the current date - this will become as of field in the dashboard. 
- [x] This Dashboard tab does not include roll ups which are being calculated on the front end.
- [x] Confirm that attendance data from previous months can live in the attendance tab of the spreadsheet, but the dashboard will only make calculations for current month. (Alternatives: delete previous months' attendance data, or copy spreadsheet template for each provider each month)
- [x] Create a single spreadsheet for all the providers who sign up

**Comment by katelovescode** [comment]
Here are the fields that I'll need:
```
child_full_name, attendance_risk, absences, earned_revenue, estimated_revenue, full_days, hours, transportation_revenue
```

**Comment by JonErvin** [comment]
Yup that's perfect!  The attendance_risk string is currently the latter ("On Track" with spaces) but either way works - if no spaces is easier let me know and I'll switch it up quickly.

For know, I don't think we'll have any transportation revenue - currently just focusing on attendance revenue.  Should we pass "0 trips - $0" in the csv or just leave blank for now?

**Comment by katelovescode** [comment]
@JonErvin @csprayregen you can pass any string to the transportation revenue, so before we're including that, do you want to pass N/A or something similar?  Also @JonErvin with the underscores would be amazing if you could!

**Comment by JonErvin** [comment]
Awesome thanks @katelovescode.  See here for a sample dashboard export, let me know how well it works: https://drive.google.com/file/d/1TEsZbBDmt4lLAzA97s59bJyDWRtgFKDP/view?usp=sharing

Three comments:
- There's actually a fourth option for an attendance risk that's "ahead_of_schedule."  It's essentially the opposite of "at_risk" where a child is attending much more frequently than his/her schedule and runs the risk of exceeding limits (but has not yet exceeded limits).
- Right now the strings have a slightly different structure.  Most notable is absences, which are "X days, Y hours" (since absences are both daily and hourly).  I also have "X of X days" for full_days and "Y of Y hours" for hours - this just adds the unit ("days" or "hours") in each cell in the table which feels more readable.  Can remove the units for full_days and hours if thats an issue though.
- I realized the current structure return rows of empty strings at the end.  Will this add any challenges or complexity?  If so, I can look into removing them (would be super easy in Python, have to imagine its possible in Sheets).

-

**Comment by katelovescode** [comment]
> * There's actually a fourth option for an attendance risk that's "ahead_of_schedule."  It's essentially the opposite of "at_risk" where a child is attending much more frequently than his/her schedule and runs the risk of exceeding limits (but has not yet exceeded limits).

Okay, I'll make sure to tweak this since I'm working on Onboarding processing now

> * Right now the strings have a slightly different structure.  Most notable is absences, which are "X days, Y hours" (since absences are both daily and hourly).  I also have "X of X days" for full_days and "Y of Y hours" for hours - this just adds the unit ("days" or "hours") in each cell in the table which feels more readable.  Can remove the units for full_days and hours if thats an issue though.

If at all possible, it'd be great to remove the units just because the UI doesn't have them, but if that's challenging I can do it in the code.  I'll fix absences, and I'll check on the string formats and make sure I'm not missing anything else

> * I realized the current structure return rows of empty strings at the end.  Will this add any challenges or complexity?  If so, I can look into removing them (would be super easy in Python, have to imagine its possible in Sheets).

This is fine, since the app splits on commas, so you don't need to change anything.  Thanks for checking!
