### ISSUE TITLE
As a user, I see a screen that tells me to check my email after I create an account

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#97]
## ✨ What new feature do you want to see?
After I click "submit" on my account sign up page, I am redirected to a screen that tells me to check and verify my email. 

## 🧶 Acceptance Criteria

- [ ] The design in the mock up is present

## 🖍️ Implementation Details
This screen follows from the account sign up described in #54 
After seeing this screen, the user checks her email and goes through the process described in #93 

## 🥧 Additional context
Figma file: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=388%3A2485
Mobile mockup: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=588%3A2935
Tablet mockup:: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=388%3A2485

**Comment by csprayregen** [comment]
@rebeccakarasiktw FYI, please link to design above when this exists.

**Comment by csprayregen** [comment]
Issues here: 

- [ ] Even when I signed up with test@test.com, the message I receive assumes I signed up with chelsea@pieforproviders.com 

- [ ] It's not clear if anything is happening when I click to re-send the email

Will do a full QA on this page, but wanted to record while I'm here. Please hold off on responding. 
![Screen Shot 2020-08-14 at 12 58 33 PM](https://user-images.githubusercontent.com/26717304/90278907-d19f6400-de2d-11ea-89ea-1ccfadf734cb.png)

**Comment by katelovescode** [comment]
cc @jontrainor couple of QA items in the design issues list!

@csprayregen for your functionality issues:

- Nothing happens when I click to re-send the email - how do I test this? Add entire flow w/ figma mock up: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=388%3A2485

This isn't implemented as a part of this ticket, and also isn't ticketed, so it'll need a new ticket, good catch.

 - Even when I signed up with test@test.com, the message I receive assumes I signed up with chelsea@pieforproviders.com'

When you say "the message I receive" do you mean "Is chelsea@pieforproviders.com your correct email"?  That's hardcoded in currently.  @jontrainor  we should pass the user's email from the form to the redirect, so we can display it correctly

- noreply email is not currently right - currently coming from tech@ so update either email or mock up

@jontrainor please change this to tech@ - the mockup is wrong :)

**Comment by jontrainor** [comment]
>Margin for bulleted text is too narrow in Large device size. In mock up, first bulleted line ends with "restart"

There are some grid styles coming from tailwind in `AuthLayout` that make this space 4 columns out of a 6 column grid. So changing this would update all the pages that use `AuthLayout` or I could do something unique for just this page like add a prop for `AuthLayout` to have a different width. 

> In mobile, header font is 36px but should be 28px (is this being handled by typography?)
 In mobile, sub-header font is 22px but should be 18 px (is this being handled by typography?)

I haven't figured out how to set a different value for each screen size in ant's global overrides yet. I can use tailwind to get this done for now. If ant doesn't support that then we might have to rely on tailwind for typography or just globally set the `font-base-size` based on screen size. It doesn't look like small vs medium/large font sizes are the same ratio in figma, but please let me know if that's not right!

>Is black font the same color? I honestly can't tell, but it has a different name in Figma

Ant uses #000000 black with 65% opacity as it's 
https://github.com/ant-design/ant-design/blob/6d02b51ae18ae7807749153db029f8351683fa10/components/style/themes/default.less#L53

I'm not sure really about the pros/cons of using opacity instead of hardcoding a value but it seems like a design system choice. I can override `text-color` in ant to be `#151515` that's in figma if you want!

> In all sizes, there is more spacing between lines than in the mock up (I'm not sure where I find the numbers to verify this, but it seems that way visually - I welcome training here!)

Ant uses a base line height of 1.5715x the font-size so that would be `line-height: 22px` for `font-size: 14px` where in figma it's `line-height: 16px`. I'll override that global value in ant so the line-height matches what's in figma.
https://github.com/ant-design/ant-design/blob/6d02b51ae18ae7807749153db029f8351683fa10/components/style/themes/default.less#L73

I'll put a pr in and can follow up with whatever you would like =)
cc: @katelovescode

**Comment by katelovescode** [comment]
> There are some grid styles coming from tailwind in `AuthLayout` that make this space 4 columns out of a 6 column grid. So changing this would update all the pages that use `AuthLayout` or I could do something unique for just this page like add a prop for `AuthLayout` to have a different width.

We're making a ticket for this; it's a little more complicated than I thought.  Changing this is outside scope for this ticket so you can skip it

> I haven't figured out how to set a different value for each screen size in ant's global overrides yet. I can use tailwind to get this done for now. If ant doesn't support that then we might have to rely on tailwind for typography or just globally set the `font-base-size` based on screen size. It doesn't look like small vs medium/large font sizes are the same ratio in figma, but please let me know if that's not right!

Made a new ticket for design, we're re-doing the fonts in `rem`, so #140 is blocked and in the backlog for now.  Changing the font sizes is out of scope for this ticket, so you can skip it

> Ant uses #000000 black with 65% opacity as it's
> https://github.com/ant-design/ant-design/blob/6d02b51ae18ae7807749153db029f8351683fa10/components/style/themes/default.less#L53

The regular font color should be `#333333`, if Figma says something different, it lies.  Let's override that Ant global in this ticket, please!

> Ant uses a base line height of 1.5715x the font-size so that would be `line-height: 22px` for `font-size: 14px` where in figma it's `line-height: 16px`. I'll override that global value in ant so the line-height matches what's in figma.
> https://github.com/ant-design/ant-design/blob/6d02b51ae18ae7807749153db029f8351683fa10/components/style/themes/default.less#L73

We are pro this decision. :D Good choice.

@jontrainor font color is the only change still needed on your QA branch, then we're good on this!
