### ISSUE TITLE
My spreadsheet shows me how many absences I have used for each child, based on my Wonderschool schedule 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#982]
## ✨ What new feature do you want to see?
We should tell the provider over the course of the month how many absences she has used. We should use her Wonderschool schedule as the default and mark a child as absent if we don't get a check in/out for that scheduled day or hour. 

## 🧶 Acceptance Criteria
- [ ] This impacts my absence count field 
- [ ] This impact my revenue estimates
- [ ] The documentation is updated to reflect this

## 🖍️ Implementation Details

Steps: 

- [x] Make changes in testing spreadsheet: https://docs.google.com/spreadsheets/d/1FKw4C6Cw0oQT6YJX8GoSZ5p4-7YaOGIxDe20tb-SaSM/edit#gid=1434675598
- [x] Update formula documentation: https://docs.google.com/document/d/1IRbjS3mgbzTA8yzR38ewg10sTsfKN-HUxr9WyLpbvAw/edit
- [x] Ask @JonErvin to QA test spreadsheet updates
- [ ] Implement in live spreadsheet (pair with Jon) 
- [ ] Final QA on live spreadsheet 

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by JTBassett** [comment]
@JonErvin I just requested access, so please let me know when that's updated. Also, do you want this to eventually replace the daily units column (D) in the "Absences" tab? I can put this as a separate column for now to help with validation.

**Comment by JonErvin** [comment]
Sweet just updated @JTBassett, let me know if you run into any issues

- Yes I think it makes sense to replace column D. I'm guessing we'll probably need to create rows for each combination of child and date too (similar to Created Daily Schedule) instead of the manual entry in column A and C.  Ultimately this should be a fully calculated sheet (i.e. no manual entry)
- Yup 1 indicates Monday.  There's a mapping table at the bottom "Other Lookup Tables" if thats helpful

**Comment by csprayregen** [comment]
@JTBassett just realized I gave you the wrong link for the test spreadsheet. Now updated above.

**Comment by katelovescode** [comment]
@JTBassett expected format for this in the dashboard upload spreadsheet is a string formatted like `"1 of 5"` - let me know if you have any questions.

**Comment by JTBassett** [comment]
Right now I have this updated in the testing spreadsheet. I know Jon should QA this, but since he is out is it helpful for @joseluisrangel-dataheim to QA this as well? I'm actually going to Florida this week (leaving this afternoon) so maybe timing will work well with both of us coming back in another week or so. When I get a chance I will also make sure to update the formula documentation.

**Comment by csprayregen** [comment]
Hey @JTBassett sorry I missed this message earlier! I'll see if Jose wants to jump in, or we can wait until Jon is back. Very much appreciated and have a great trip!

**Comment by JTBassett** [comment]
@joseluisrangel-dataheim I know we will go over this tomorrow evening, but @JonErvin you are also good to review it as I finished adding it to the documentation last night. Below is a summary of the main changes for more context.

**Summary of Updates**
**Wonderschool ID**
Added reference from the first column for ease of use with Absence Calculations

**Wonderschool Attendance Upload**
Calculated Helper field: Reference for Absence Calculations
Calculated Hours field: checked_out_at - checked_in_at in hours

**(New) Absences Map**
(Used for reference rather than calculations)
Schedule-related data: ID, DateValue, and "Helper" field for matching
Absence-related data: Date, Day of the Week, and headers for each child ID

**Absences**
Added Wonderschool ID and remainder of data is now generated automatically through lookups

**Created Daily Schedule**
Added following fields to power Absences tab: Scheduled Total Hours, ID For Mapping, Attended?, Hours Attended, and Hours Absent

More details around of each of these is included in the docs!

**Comment by JTBassett** [comment]
Jose will QA this weekend

**Comment by JTBassett** [comment]
Jose QA'd and said it's good to go - I hid the absence map tab to reduce complexity looking through the sheet tabs. Once @JonErvin reviews it as well, we should be good to move forward.

**Comment by csprayregen** [comment]
Great! @JonErvin if you don't get to this before Monday, feel free to find time to implement this in production with JT while I'm gone (though if you have anything you'd rather wait to discuss with me, that's fine too).

**Comment by JonErvin** [comment]
Hey @JTBassett just realized I was the blocker for this one - sorry for being MIA, I think I missed this thread while I was out.  Just went through the updates - really cool way to implement this!  I've never seen the QUERY and FILTER combination used in a spreadsheet like this - looks awesome overall in my opinion and I may borrow this strategy in the future.  Tested it out and seems like it works great.  Also thank you for the super clear summary of changes!

I have a couple suggestions, mostly just for maintaining this down the road:

**Wonderschool ID**: Do we need this extra column?  From a DRY ("don't repeat yourself") perspective, wondering if we could avoid repeat that manual entry column?

**Wonderschool Attendance Upload**: In a similar vein, I'm wondering if we can refer to existing columns in Daily Calculation rather than add these columns?  This would help us keep data entry (blue tabs) separate from back end calculations (orange tabs).  Specifically, I'm thinking:
- Hours could use Calculated Hours (col P) in Daily Calculation (this also handles missing checkout)
- Helper could use ChildCheckIn (I think this has the same function, but I might be missing something)

**Absences**: No actual changes this implementation is awesome - can we make sure it's documented though?  Took me a minute to follow the formulas and would want to make sure its easy to build into the app.

Then finally, I just changed the font to black to show that its a calculated field, changed the tab color to orange and moved it up ahead of Inputs to S3.  This is purely aesthetic but could be helpful in separating input, calcs, and outputs.  Let me know if this is OK.

Thanks again JT!  Hit me up on Slack if I can clarify anything here.

**Comment by JTBassett** [comment]
@JonErvin I just finished updating the formulas and docs to reflect your suggestions. An updated summary of updates is provided below for reference.

**Summary of Updates**

**(New) Absences Map**
(Used for reference rather than calculations)
Schedule-related data: ID, DateValue, and "Helper" field for matching
Absence-related data: Date, Day of the Week, and headers for each child ID

**Absences**
Added Wonderschool ID and remainder of data is now generated automatically through lookups (queries/filters)

**Created Daily Schedule**
Added the following fields to power Absences tab: Scheduled Total Hours, ID For Mapping, Attended?, and Hours Attended

**Daily Calculation**
Added (or moved from previous reference in Wonderschool Attendance Upload tab) Attendance Helper field for Absence tracker to reference.

**Comment by JonErvin** [comment]
Hey thanks @JTBassett!  This looks good, thanks for making these changes.

In reviewing again, I noticed a potential issue with the Absences tab QUERY.  Right now, if the date is set to the middle of the month (say 2/20/20), the created daily schedule will still be created for the full month.   In this hypothetical situation, we would only have attendance data through 2/20 (since that's the current date) and the model would flag all scheduled days from 2/21-2/29 as absent.  **I think need to add a filter for the current data in the Absences tab - would you agree?**

Also - just for understanding, are you planning on moving the Absences Map to the NECC production model?  From what I know, I'm not sure if its necessary, but you're closer to this than I am and I trust what you think is best here.

**Comment by JTBassett** [comment]
I updated the Absences tab to account for the date and updated the documentation. I also removed the "Absences Map" altogether so as not to clutter the spreadsheet.

**Comment by JonErvin** [comment]
Nice!  Thanks @JTBassett this looks great.  Ready to move to production from a QA standpoint.

@csprayregen want to confirm we're good to pass this update to the live dashboard since it will immediately impact user's views (i.e. they'll suddenly see absences).  In terms of user expectations, do we need to do anything to give users a heads up for a changes like this or do they just understand that its a pilot and things change pretty quickly?

**Comment by JTBassett** [comment]
Leaving a reminder to myself to update the absences and summary by child tabs to reflect the maximum units that occur within at most 5 absences per child.

**Comment by JTBassett** [comment]
@JonErvin with the five max absences, do you know how this plays out for hourly units? For example, if I miss an hour one day and two the next, is this two separate "instances" that contributes to the five absence limit? If so, we may have to add a field that tracks not only hourly absence hours but hourly absence instances. And I would assume the daily unit is preferred because it generates more revenue? It may be helpful to sync on this again, because it's looking more complex as I dig into it.

**Comment by JonErvin** [comment]
Hey @JTBassett happy to sync back up!  I'm actually heading out for a wedding later this weekend, but I'll be back Sunday and free most evenings next week too.

To your question, I think you're right in considering each "instance" - I would define an instance as any situation in which the child is scheduled for > 0 hours but attends 0 hours (i.e. does not attend at all).  So for example if this is Jimmy Smith's schedule:
 - M: 8 hrs
 - T: 3 hrs
 - W: 8 hrs
 - Th: 3 hrs
 - F: 8 hrs

And he attends:
- T: 3 hrs
- W: 4 hrs
- F: 8 hrs

We would have two instances of absence - Monday and Thursday.  This would mean 1 day unit of absence (for Monday) and 3 hourly units (for Thursday). This would mean 2 of 5 absences for the month have been used.  Attending a partial day on Wednesday would not count toward this absence.

Let me know if this helps at all - super happy to sync again once I'm back as well as respond to comments here in the meantime.  And most importantly thanks for thinking one of the most surprisingly complex tickets so far!

**Comment by JTBassett** [comment]
@JonErvin I tested our updates in the Summary by Child tab and it appears to be working as expected! I will make sure to update the documentation as well. The new summary is below:

**Absences**
Added Wonderschool ID and remainder of data is now generated automatically through lookups (queries/filters)

**Created Daily Schedule**
Added the following fields to power Absences tab: Scheduled Total Hours, ID For Mapping, Attended?, and Hours Attended

**Daily Calculation**
Added (or moved from previous reference in Wonderschool Attendance Upload tab) Attendance Helper field for Absence tracker to reference.

**Summary by Child**
Updated daily unit and hour unit absences fields to account for inclusion flag field in absences tab (limiting to top 5 occurrences)

**Comment by JonErvin** [comment]
Fantastic!  Thanks so much JT, this all works well.  One ticky-tacky edit - @JTBassett can we remove the `MIN( ____, AbsencesLimit)` in Absences (Daily units) in Summary By Child?  I think its redundant now that we check for the limit in the Absences tab. Doesn't impact functionality but just cleans this up a bit.  If you agree, we should make this change in [docs](https://docs.google.com/document/d/1IRbjS3mgbzTA8yzR38ewg10sTsfKN-HUxr9WyLpbvAw/edit#heading=h.2xhfv2d58mqa) too

One think I'd love to think quickly on before we move to production is what we show users.  Say for example a child misses 3 full days and 2 partial, 3-hour days.  Right now the dashboard would show _"3 days, 6 hours"_ which might be confusing, since she's used all 5 absences days, translating into 3 daily units, and 6 hourly units.  @csprayregen any thoughts on what's most helpful to users here?  I'm thinking _"5 days (3 daily units, 6 hourly units)"_ might be info overload...

**Comment by csprayregen** [comment]
@JonErvin my initial thought is that that's actually the right info to share, but curious if you have any input @rebeccakarasiktw

**Comment by JTBassett** [comment]
@JonErvin I fixed what you mentioned last week. Did you come to any other conclusions about the view you mentioned in the second paragraph?

**Comment by JonErvin** [comment]
Confirming that this is now live in production!  Thanks again @JTBassett. 

For recordkeeping, copying in the decision on formatting to the question above (from Slack):

_The absence column should just read “3 of 5” or “0 of 5" and that it should reflect the absences used, without reference to whether they are partial or full days. The amount billed for in those absences would be implied in the revenue estimates._
